version: '3.6'
services:
  gateone:
    image: arush/gateone:http
    ports:
    - "8080:8000"
    hostname: kubectl
    networks:
    - frontend
    volumes:
    - ssh_key:/root/.ssh/
    - kube_config:/root/.kube/
    restart: always
  lab:
    image: arush/cka_lab
    ports:
    - "80:80"
    networks:
    - frontend
    restart: always
networks:
  frontend: {}
volumes:
  ssh_key: {}
  kube_config: {}
